version: '3.7'
services:
  odoo-stack:
    container_name: odoo-stack
    build:
      context: ./dockerfile
      dockerfile: odoo.Dockerfile
    # environment: 
    #   -  HOST=database-stack
    #   -  PORT=5432
    #   -  USER=odoo
    #   -  PASSWORD=odoo
    volumes:
      - ./addons-extra:/mnt/addons-extra
      - ./odoo-config:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    ports:
      - 8069:8069
    depends_on:
      - database-stack
    restart: always

  database-stack:
    container_name: database-stack
    image: postgres:latest
    volumes:
      - database-stack-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    #command: -p 5433
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always

  pgadmin-stack:
    container_name: pgadmin-stack
    image: dpage/pgadmin4:5.4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 8080:80
    links:
      - 'database-stack:pgsql-server'
    environment:
      PGADMIN_DEFAULT_EMAIL: lado.grigalashvili@gmail.com
      PGADMIN_DEFAULT_PASSWORD: odoo
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - database-stack
    restart: always

  nginx-stack:
    container_name: nginx-stack
    build:
      context: ./dockerfile
      dockerfile: nginx.Dockerfile
    volumes:
      - ./nginx-config:/mnt/etc/nginx/conf.d
    ports:
      - 80:80 #non secure
      - 443:443 #ssl
    depends_on:
      - odoo-stack
    restart: always

volumes:
  odoo-web-data:
  database-stack-data:
  pgadmin-data:

# networks:
#   odoonetwork:
#      driver: bridge